name: Deploy with Secrets
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # DEBUG: List files before changes
      - name: List files (before)
        run: ls -la

      # Replace placeholders
      - name: Inject Secrets
        run: |
          echo "Formspree Endpoint: ${{ secrets.FORMSPREE_ENDPOINT }}"
          echo "reCAPTCHA Key: ${{ secrets.RECAPTCHA_SITE_KEY }}"
          
          find . -type f -name "*.html" -exec sed -i \
            "s|FORMSPREE_ENDPOINT_PLACEHOLDER|https://formspree.io/f/${{ secrets.FORMSPREE_ENDPOINT }}|g" {} \;
          
          find . -type f -name "*.html" -exec sed -i \
            "s|RECAPTCHA_SITE_KEY_PLACEHOLDER|${{ secrets.RECAPTCHA_SITE_KEY }}|g" {} \;

      # DEBUG: Verify changes
      - name: Verify replacements
        run: |
          grep -r "formspree.io" . || echo "Formspree replacement FAILED"
          grep -r "data-sitekey=\"6L" . || echo "reCAPTCHA replacement FAILED"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
