name: Deploy with Secrets
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Inject Secrets
        run: |
          # Force replacement in all HTML files
          find . -type f -name "*.html" -exec sed -i "s|FORMSPREE_ENDPOINT_PLACEHOLDER|${{ secrets.FORMSPREE_ENDPOINT }}|g" {} \;
          echo "Replacement done. Checking:"
          grep -r "formspree.io" . || echo "Replacement failed"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
