name: Deploy with Secrets
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Debug: Verify secrets are accessible
      - name: Check Secrets
        run: |
          echo "FORMSPREE_ENDPOINT exists: ${{ secrets.FORMSPREE_ENDPOINT != '' }}"
          echo "RECAPTCHA_SITE_KEY exists: ${{ secrets.RECAPTCHA_SITE_KEY != '' }}"

      # Replace placeholders
      - name: Inject Secrets
        run: |
          find . -type f -name "*.html" -exec sed -i \
            "s|FORMSPREE_ENDPOINT_PLACEHOLDER|https://formspree.io/f/${{ secrets.FORMSPREE_ENDPOINT }}|g" {} \;
          find . -type f -name "*.html" -exec sed -i \
            "s|RECAPTCHA_SITE_KEY_PLACEHOLDER|${{ secrets.RECAPTCHA_SITE_KEY }}|g" {} \;

      # Verify replacements
      - name: Verify Changes
        run: |
          grep -r "formspree.io" . || echo "Error: Formspree replacement failed!"
          grep -r "6L" . || echo "Error: reCAPTCHA replacement failed!"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
