name: Deploy with Secrets
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push to gh-pages branch
    steps:
      - uses: actions/checkout@v4
      
      - name: Inject Secrets
        run: |
          sed -i "s|FORMSPREE_ENDPOINT_PLACEHOLDER|${{ secrets.FORMSPREE_ENDPOINT }}|g" index.html
          sed -i "s|RECAPTCHA_SITE_KEY_PLACEHOLDER|${{ secrets.RECAPTCHA_SITE_KEY }}|g" index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
